### ISSUE TITLE
ffmpeg 编译 --enable-libuavs3d 参数失败

### ISSUE THREAD

**Issue by lijingchang** [uavs3/uavs3d#11]
环境ubuntu 14.04，make && makeinstall 之后，编译ffmpeg 配置 --enable-libuavs3d 参数失败。

错误提示：ERROR: uavs3d >= 1.1.41 not found using pkg-config

**Comment by lijingchang** [comment]
![Q@VLGC LDK6)~`A{O@G %SB](https://user-images.githubusercontent.com/5574905/113085995-61eeb580-9213-11eb-872e-068dcc7cf02e.png)
提示不兼容，然后我想编译uavs3d android的版本，提示以下错误

`/android-ndk-r21b/build/ndk-build: line 151: file: command not found
/usr/bin/make: invalid option -- 'O'
Usage: make [options] [target] ...`

**Comment by hanbingjie515** [comment]
> 环境ubuntu 14.04，make && makeinstall 之后，编译ffmpeg 配置 --enable-libuavs3d 参数失败。
> 
> 错误提示：ERROR: uavs3d >= 1.1.41 not found using pkg-config

首先，确认是否已安装gawk，可以运行version.sh 看是否出现“./version.sh: line 18: gawk: command not found”
然后，确认uavs3d.pc中Version值是否正常
最后，确认uavs3d.pc是否被configure程序识别

**Comment by lijingchang** [comment]
> > 环境ubuntu 14.04，make && makeinstall 之后，编译ffmpeg 配置 --enable-libuavs3d 参数失败。
> > 错误提示：ERROR: uavs3d >= 1.1.41 not found using pkg-config
> 
> 首先，确认是否已安装gawk，可以运行version.sh 看是否出现“./version.sh: line 18: gawk: command not found”
> 然后，确认uavs3d.pc中Version值是否正常
> 最后，确认uavs3d.pc是否被configure程序识别

感谢解答，经确认uavs3d.pc可以识别，但是指向的.so是Linux方式编译的，里面的一些方法与Andorid程序不兼容。编译的时候我把Android方式编译出来的so加到环境里就可以了

**Comment by zhongyuanceshi** [comment]
> > > 环境ubuntu 14.04，make && makeinstall 之后，编译ffmpeg 配置 --enable-libuavs3d 参数失败。
> > > 错误提示：ERROR: uavs3d >= 1.1.41 not found using pkg-config
> > 
> > 
> > 首先，确认是否已安装gawk，可以运行version.sh 看是否出现“./version.sh: line 18: gawk: command not found”
> > 然后，确认uavs3d.pc中Version值是否正常
> > 最后，确认uavs3d.pc是否被configure程序识别
> 
> 感谢解答，经确认uavs3d.pc可以识别，但是指向的.so是Linux方式编译的，里面的一些方法与Andorid程序不兼容。编译的时候我把Android方式编译出来的so加到环境里就可以了

can you give me a sh file for android?
