### ISSUE TITLE
Not GPL compatible

### ISSUE THREAD

**Issue by xatabhk** [uavs3/uavs3d#26]
(https://github.com/ietf-wg-cellar/matroska-specification/pull/573#issuecomment-1013828067)
The AVS3 won't be used in contribs of many popular tools/players as it's a BSD 4-clause license, meaning it needs an "advertising" in the software with a copyright notice. This is incompatible with GPL code. Would it be possible to relicense the code to a different license like the BSD 3-clause that is GPL compatible ?

**Comment by robUx4** [comment]
The goal would we to have proper support in VLC (out of the box). Even FFmpeg support would benefit from it.

**Comment by hanbingjie515** [comment]
Thanks for your advices. The license has been changed to BSD 3-clause.

**Comment by robUx4** [comment]
Wow, great news !
