### ISSUE TITLE
Please fix warnings

### ISSUE THREAD

**Issue by pashamcr** [uavs3/uavs3d#3]
Please place the brackets correctly to fix: _warning: '&&' within '||' [-Wlogical-op-parentheses]_

it’s clear here:
_decore/deblock.c:618
decore/inter_pred.c str:538
decoder/parser.c:2320_

it’s not clear here:
_decoder/parser.c:500_
`    while ((dec_bs_next(bs, 32) == 0x1B5) || (dec_bs_next(bs, 32) == 0x1B2) && bs->cur <= bs->end)`
to
`    while (((dec_bs_next(bs, 32) == 0x1B5) || (dec_bs_next(bs, 32) == 0x1B2)) && (bs->cur <= bs->end))`
or
`    while ((dec_bs_next(bs, 32) == 0x1B5) || ((dec_bs_next(bs, 32) == 0x1B2) && (bs->cur <= bs->end)))`

Please fix: _warning: format specifies type 'long long' but the argument has type 's64' (aka 'long') [-Wformat]_
decoder/dec_util.c:1463
`        printf(" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  Warnning: enc/dec mismatch! ptr = %lld\n", pic->ptr);`
to
`        printf(" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  Warnning: enc/dec mismatch! ptr = %ld\n", pic->ptr);`

**Comment by hanbingjie515** [comment]
Thanks! Warnings have been fixed.
