### ISSUE TITLE
avs+、avs2（4k）

### ISSUE THREAD

**Issue by azureplus** [uavs3/uavs3d#6]
Whether to support avs+, avs2 (4k) decoding

**Comment by hanbingjie515** [comment]
Sorry, uavs3d is a decoder for AVS3-P2 baseline profile which is not compatible with AVS+ or AVS2.

**Comment by azureplus** [comment]
> Sorry, uavs3d is a decoder for AVS3-P2 baseline profile which is not compatible with AVS+ or AVS2.

Do you have these open source decoding libraries?

**Comment by hanbingjie515** [comment]
AVS2 decoder: https://github.com/pkuvcl/davs2
AVS2 encoder: https://github.com/pkuvcl/xavs2
